### PR TITLE
Purely styleguide 

### PR DESCRIPTION
**Pull request by apurvis**
No substantive changes
@jarthod

### CODE REVIEW

**Comment by apurvis** [comment]
not sure what's up with the travis build all of a sudden it's complaining about missing environment variables

**Comment by jarthod** [comment]
No the problem is Rails 5, it tries to bundle with activesupport 5.0 now that it is released and fails with:
```
Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
```
And with ruby >= 2.2.2 it fails with:
```
uninitialized constant ActiveSupport::Deprecation (NameError)
```

So that means we should probably:
- Update the code to be compatible with rails 5
- Update the matrix to build against both AS 4 and 5 (only with recent ruby for 5)

**Comment by apurvis** [comment]
OK well for now I'm just limiting the activesupport gem version.  my organization is still upgrading to rails 4 so rails 5 is not going to be an issue anytime in the next few years for me; if someone needs that they'll have to upgrade the gem

**Comment by apurvis** [comment]
ok the build is passing now; guess this is worth releasing lest other people have bundler issues.  i pushed a version number change.

**Comment by jarthod** [comment]
Released `6.2.3`

**Pull request merged**
