### PR TITLE
Fix the 'other' answer parsing in situations where the response is ... lacking

### PR DESCRIPTION
**Pull request by apurvis**
[as described here](https://github.com/jarthod/survey-gizmo-ruby/pull/77#issuecomment-230069073)

@jarthod @kjhenner

### CODE REVIEW

**Comment by apurvis** [comment]
i'm mildly concerned that this will strip out valid answers somehow but at the same time i can't think of a way that could happen.

**Comment by jarthod** [comment]
What the fuck is wrong with them xD

**Comment by jarthod** [comment]
I've never seen that so I'm trusting you and releasing `6.2.4` ☺

**Comment by apurvis** [comment]
i only just saw it for the first time.  contemplating reporting it to
support but it's probably pointless at least as re: v4 since they're now on
v5

**Comment by apurvis** [comment]
it appears this happens when you have a checkbox question and more than one of the checkboxes can have "other" text.

**Pull request merged**
