### PR TITLE
Loosen the activesupport version

### PR DESCRIPTION
**Pull request by apurvis**
Now that https://github.com/jarthod/survey-gizmo-ruby/pull/96 is merged, i think this requirement can be loosened (@jmcnevin has a fork where he already put these two things together)

### CODE REVIEW

**Comment by apurvis** [comment]
hmm i guess active_support 5.1 is not supported on ruby 2.0... so the build is failing.  we should probably drop ruby 2.0 support; thoughts?

**Comment by jarthod** [comment]
Well if we want to do it right we should actually test multiple ActiveSupport versions, like we did on https://github.com/Intrepidd/working_hours/blob/master/.travis.yml: https://travis-ci.org/Intrepidd/working_hours
To make sure we don't break AS4 support later.

**Comment by jarthod** [comment]
Otherwise we can just remove 2.0 yeah ^^

**Comment by tisba** [comment]
That's of course a maintainers decision, but since support for Ruby 2.0 (and even 2.1) has ended quite a while ago, I think it's quite okay to drop it.

Would love to see this merged ❤️  :)

**Comment by jarthod** [comment]
Yeah my point is not really about 2.0 actually but more about testing AS4 as this is the main version right now, this more important, and if we test AS4 well we can leave 2.0 it won't hurt ☺

**Comment by apurvis** [comment]
i agree it would be nice to test AS4 vs. AS5 but the usage in the gem is so minimal i personally am not sure its worth the effort.

**Comment by apurvis** [comment]
released

**Pull request merged**
