### PR TITLE
Fix retries

### PR DESCRIPTION
**Pull request by apurvis**
So I sorted this out in a different project, but basically the Faraday retry middleware only handles timeouts on the request side. Once you get into the response processing, that retry won't actually help you, which is kind of a problem for rate limit exceeded errors.

@jarthod

### CODE REVIEW

**Comment by jarthod** [comment]
[Not yet another dependency](http://www.mikeperham.com/2016/02/09/kill-your-dependencies/) :'(

**Comment by apurvis** [comment]
yeah but at least it's more community supported than `Pester` was.  definitely don't want to get into the business of writing retry logic anew.

**Comment by apurvis** [comment]
(what really sucks IMHO is that active_support doesn't just have retries builtin)

**Comment by jarthod** [comment]
Yes it's better supported, as long as it does the job ;)

**Comment by apurvis** [comment]
maybe don't merge this yet; haven't tested thoroughly.  will report back in a few days.

**Comment by jarthod** [comment]
Ok thanks ;)

**Comment by apurvis** [comment]
K looks good; had to change the Retriable gem to 1.4 for our own dependency hell.

**Comment by jarthod** [comment]
Thanks. released `6.1.0`

**Pull request merged**
