### PR TITLE
Fix option id 0

### PR DESCRIPTION
**Pull request by apurvis**
I was seeing this in my data
```
"[question(12), option(0)]"=>"2496955"}"
```
which was parsing to option_id 0 and throwing away the value.

cc @mkaydev @rfroetscher

### CODE REVIEW

**Comment by apurvis** [comment]
@jarthod if you could push a release that would be great no rush

**Comment by jarthod** [comment]
Sure, just released `6.2.12`

What's your rubygems email? I'll give you the push rights.

**Comment by apurvis** [comment]
https://rubygems.org/profiles/maldororestmort

**Comment by jarthod** [comment]
Thanks, you can now release ;)

**Pull request merged**
